package com.beet.backend.modules.inventory.domain.usecase;

import com.beet.backend.modules.inventory.domain.api.InventoryServicePort;
import com.beet.backend.modules.inventory.domain.exception.IngredientAlreadyActivatedException;
import com.beet.backend.modules.inventory.domain.exception.IngredientOwnershipException;
import com.beet.backend.modules.inventory.domain.exception.IngredientStockNotFoundException;
import com.beet.backend.modules.inventory.domain.model.InventoryStockDomain;
import com.beet.backend.modules.inventory.domain.model.InventoryTransactionDomain;
import com.beet.backend.modules.inventory.domain.model.TransactionReason;
import com.beet.backend.modules.inventory.domain.spi.InventoryPersistencePort;
import com.beet.backend.modules.ingredient.domain.spi.IngredientPersistencePort;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class InventoryUseCase implements InventoryServicePort {

    private final InventoryPersistencePort inventoryPort;
    private final IngredientPersistencePort ingredientPort;

    @Override
    @Transactional
    public InventoryStockDomain activate(InventoryStockDomain stock, UUID ownerId, UUID userId) {
        // 1. Validate ingredient belongs to the owner's catalog
        if (!ingredientPort.existsByIdAndOwnerId(stock.getMasterIngredientId(), ownerId)) {
            throw IngredientOwnershipException.forIngredient(stock.getMasterIngredientId().toString());
        }

        // 2. Check not already activated in this restaurant
        if (inventoryPort.existsByIngredientAndRestaurant(stock.getMasterIngredientId(), stock.getRestaurantId())) {
            throw IngredientAlreadyActivatedException.forIngredient(
                    stock.getMasterIngredientId().toString(), stock.getRestaurantId().toString());
        }

        // 3. Save stock entry (ID auto-generated by DB, audit fields by Spring Data)
        InventoryStockDomain savedStock = inventoryPort.saveStock(stock);

        // 4. Log initial transaction
        InventoryTransactionDomain transaction = InventoryTransactionDomain.builder()
                .ingredientStockId(savedStock.getId())
                .delta(stock.getCurrentStock())
                .reason(TransactionReason.INITIAL)
                .previousStock(BigDecimal.ZERO)
                .resultingStock(stock.getCurrentStock())
                .notes("Initial stock activation")
                .createdBy(userId)
                .build();

        inventoryPort.saveTransaction(transaction);

        return savedStock;
    }

    @Override
    public List<InventoryStockDomain> listStocks(UUID restaurantId) {
        return inventoryPort.findAllStocksByRestaurant(restaurantId);
    }

    @Override
    @Transactional
    public InventoryTransactionDomain adjustStock(UUID stockId, BigDecimal value,
            boolean isReplace, TransactionReason reason,
            String notes, UUID userId) {
        InventoryStockDomain stock = inventoryPort.findStockById(stockId)
                .orElseThrow(() -> IngredientStockNotFoundException.forId(stockId.toString()));

        BigDecimal previousStock = stock.getCurrentStock();
        BigDecimal delta;
        BigDecimal resultingStock;

        if (isReplace) {
            // REPLACE mode: user provides the new absolute stock value
            resultingStock = value;
            delta = value.subtract(previousStock);
        } else {
            // DELTA mode: user provides the change (+5, -3)
            delta = value;
            resultingStock = previousStock.add(value);
        }

        // Update the stock (raw JDBC for targeted single-column update)
        inventoryPort.updateCurrentStock(stockId, resultingStock, userId);

        // Log the transaction
        InventoryTransactionDomain transaction = InventoryTransactionDomain.builder()
                .ingredientStockId(stockId)
                .delta(delta)
                .reason(reason)
                .previousStock(previousStock)
                .resultingStock(resultingStock)
                .notes(notes)
                .createdBy(userId)
                .build();

        return inventoryPort.saveTransaction(transaction);
    }

    @Override
    public List<InventoryTransactionDomain> getTransactions(UUID stockId) {
        return inventoryPort.findTransactionsByStockId(stockId);
    }
}
